#!/usr/bin/env python

import sys
from PySide.QtCore import QUrl
from PySide.QtGui import QApplication
from PySide.QtWebKit import QWebView, QWebPage

url = "http://dev.qsnake.com/"

app = QApplication(sys.argv)

web = QWebView()
web.setWindowTitle("Qsnake Desktop Application")
web.load(QUrl(url))
web.show()

sys.exit(app.exec_())
